"""update script model

Revision ID: 34b3d41af2fb
Revises: f752680a1ba9
Create Date: 2024-09-24 10:59:22.404971

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "34b3d41af2fb"
down_revision = "f752680a1ba9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ask_count_limit",
                sa.Integer(),
                nullable=False,
                comment="Ask count limit",
            )
        )
        batch_op.add_column(
            sa.Column(
                "ask_model",
                sa.String(length=255),
                nullable=False,
                comment="Ask count model",
            )
        )
        batch_op.add_column(
            sa.Column("ask_prompt", sa.Text(), nullable=False, comment="Ask Prompt")
        )
        batch_op.add_column(
            sa.Column(
                "ask_with_history",
                sa.Integer(),
                nullable=False,
                comment="Ask with history Count",
            )
        )

    with op.batch_alter_table("ai_lesson_script", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ask_with_history",
                sa.Integer(),
                nullable=False,
                comment="Ask with history Count",
            )
        )
        batch_op.alter_column(
            "ask_prompt",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.Text(),
            existing_comment="Ask count history",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_lesson_script", schema=None) as batch_op:
        batch_op.alter_column(
            "ask_prompt",
            existing_type=sa.Text(),
            type_=mysql.INTEGER(display_width=11),
            existing_comment="Ask count history",
            existing_nullable=False,
        )
        batch_op.drop_column("ask_with_history")

    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.drop_column("ask_with_history")
        batch_op.drop_column("ask_prompt")
        batch_op.drop_column("ask_model")
        batch_op.drop_column("ask_count_limit")

    # ### end Alembic commands ###
