"""update profile item

Revision ID: 4562bef00e0d
Revises: 79bafff21efb
Create Date: 2025-05-13 06:51:33.280260

"""

# revision identifiers, used by Alembic.
revision = "4562bef00e0d"
down_revision = "79bafff21efb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
