"""update discount model

Revision ID: 551f8f3b9ecb
Revises: 3fd3cf30dc22
Create Date: 2024-08-11 08:12:55.247745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '551f8f3b9ecb'
down_revision = '3fd3cf30dc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_course_buy_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='Discount value'))
        batch_op.alter_column('pay_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Payment value',
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('ai_lesson', schema=None) as batch_op:
        batch_op.drop_column('lesson_sale_type')

    with op.batch_alter_table('ai_lesson_script', schema=None) as batch_op:
        batch_op.alter_column('script_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Script UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_prompt',
               existing_type=mysql.TEXT(),
               comment='Script prompt',
               existing_comment='Script content',
               existing_nullable=False)
        batch_op.alter_column('script_model',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Script model',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_temprature',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Script Temprature',
               existing_nullable=False,
               existing_server_default=sa.text("'0.80'"))
        batch_op.alter_column('script_check_flag',
               existing_type=mysql.TEXT(),
               nullable=False,
               comment='Script check flag')
        batch_op.alter_column('script_ui_profile',
               existing_type=mysql.TEXT(),
               comment='Script UI profile',
               existing_comment='Script check content',
               existing_nullable=False)
        batch_op.alter_column('script_other_conf',
               existing_type=mysql.TEXT(),
               comment='Other configurations of the script',
               existing_comment='脚本的其他配置',
               existing_nullable=False)
        batch_op.drop_index('idx_lesson_id_ai_lesson_script')
        batch_op.drop_index('idx_script_id_ai_lesson_script')

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_apply_type', sa.Integer(), nullable=False, comment='Discount apply type: 801-all, 802-specific'))
        batch_op.alter_column('discount_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Discount type: 701-fixed, 702-percent',
               existing_comment='Discount type: 0-percent, 1-amount',
               existing_nullable=False)
        batch_op.alter_column('discount_generated_user',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=36),
               existing_comment='Discount generated user',
               existing_nullable=False)

    with op.batch_alter_table('user_conversion', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_source',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               comment='Conversion type',
               existing_comment='Conversion Source ',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_conversion_id_user_conversion')
        batch_op.drop_index('idx_conversion_uuid_user_conversion')
        batch_op.drop_index('idx_user_id_user_conversion')

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('default_model',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               comment='Default model',
               existing_comment='gpt model ',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4-0613'"))
        batch_op.alter_column('user_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='User_state',
               existing_comment='user state',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='user sex',
               existing_comment='0-default ,1-male,2-female',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_birth',
               existing_type=sa.DATE(),
               nullable=True,
               comment='user birth',
               existing_comment='birth',
               existing_server_default=sa.text("'1984-01-01'"))
        batch_op.alter_column('user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='user avatar',
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_email_user_info')
        batch_op.drop_index('idx_mobile_user_info')
        batch_op.drop_index('idx_username_user_info')
        batch_op.create_index(batch_op.f('ix_user_info_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_info_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('profile_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0 default, 1 system configuration, 2 user configuration, 3 course configuration',
               existing_comment='0 默认,1 系统配置,2 用户配置，3 课程配置',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('idx_user_id_user_profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_user_profile', ['user_id'], unique=False)
        batch_op.alter_column('profile_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0 默认,1 系统配置,2 用户配置，3 课程配置',
               existing_comment='0 default, 1 system configuration, 2 user configuration, 3 course configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_info_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_info_mobile'))
        batch_op.create_index('idx_username_user_info', ['username'], unique=False)
        batch_op.create_index('idx_mobile_user_info', ['mobile'], unique=False)
        batch_op.create_index('idx_email_user_info', ['email'], unique=False)
        batch_op.alter_column('user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='user avatar',
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_birth',
               existing_type=sa.DATE(),
               nullable=False,
               comment='birth',
               existing_comment='user birth',
               existing_server_default=sa.text("'1984-01-01'"))
        batch_op.alter_column('user_sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='0-default ,1-male,2-female',
               existing_comment='user sex',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='user state',
               existing_comment='User_state',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('default_model',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               comment='gpt model ',
               existing_comment='Default model',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4-0613'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('user_conversion', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_user_conversion', ['user_id'], unique=False)
        batch_op.create_index('idx_conversion_uuid_user_conversion', ['conversion_uuid'], unique=False)
        batch_op.create_index('idx_conversion_id_user_conversion', ['conversion_id'], unique=False)
        batch_op.alter_column('conversion_uuid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_source',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               comment='Conversion Source ',
               existing_comment='Conversion type',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.alter_column('discount_generated_user',
               existing_type=sa.String(length=36),
               type_=mysql.BIGINT(display_width=20),
               existing_comment='Discount generated user',
               existing_nullable=False)
        batch_op.alter_column('discount_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Discount type: 0-percent, 1-amount',
               existing_comment='Discount type: 701-fixed, 702-percent',
               existing_nullable=False)
        batch_op.drop_column('discount_apply_type')

    with op.batch_alter_table('ai_lesson_script', schema=None) as batch_op:
        batch_op.create_index('idx_script_id_ai_lesson_script', ['script_id'], unique=False)
        batch_op.create_index('idx_lesson_id_ai_lesson_script', ['lesson_id'], unique=False)
        batch_op.alter_column('script_other_conf',
               existing_type=mysql.TEXT(),
               comment='脚本的其他配置',
               existing_comment='Other configurations of the script',
               existing_nullable=False)
        batch_op.alter_column('script_ui_profile',
               existing_type=mysql.TEXT(),
               comment='Script check content',
               existing_comment='Script UI profile',
               existing_nullable=False)
        batch_op.alter_column('script_check_flag',
               existing_type=mysql.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='Script check flag')
        batch_op.alter_column('script_temprature',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Script Temprature',
               existing_nullable=False,
               existing_server_default=sa.text("'0.80'"))
        batch_op.alter_column('script_model',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Script model',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_prompt',
               existing_type=mysql.TEXT(),
               comment='Script content',
               existing_comment='Script prompt',
               existing_nullable=False)
        batch_op.alter_column('lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Script UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_sale_type', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='0 默认 1 体验课 2 系统课 3 扩展课'))

    with op.batch_alter_table('ai_course_buy_record', schema=None) as batch_op:
        batch_op.alter_column('pay_value',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Payment value',
               existing_nullable=False,
               existing_server_default=sa.text("'0.00'"))
        batch_op.drop_column('discount_value')

    # ### end Alembic commands ###
