"""add log ui

Revision ID: 633a2f94f6d7
Revises: f2bda1a75fe9
Create Date: 2025-01-07 06:04:22.992962

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "633a2f94f6d7"
down_revision = "f2bda1a75fe9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course_lesson_attendscript", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "script_ui_conf", sa.Text(), nullable=False, comment="Script UI Config"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course_lesson_attendscript", schema=None) as batch_op:
        batch_op.drop_column("script_ui_conf")

    # ### end Alembic commands ###
