"""add discount name to discount record

Revision ID: 72e53bce45e5
Revises: fc59dc263a7f
Create Date: 2024-08-18 07:45:59.858111

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72e53bce45e5"
down_revision = "fc59dc263a7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("discount_record", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "discount_name",
                sa.String(length=255),
                nullable=False,
                comment="Discount name",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("discount_record", schema=None) as batch_op:
        batch_op.drop_column("discount_name")

    # ### end Alembic commands ###
