"""add order paid value

Revision ID: 76e1aa0b6bcb
Revises: a1913820566f
Create Date: 2024-08-18 05:17:36.077466

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76e1aa0b6bcb"
down_revision = "a1913820566f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course_buy_record", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "paid_value",
                sa.Numeric(precision=10, scale=2),
                nullable=False,
                comment="Paid value",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course_buy_record", schema=None) as batch_op:
        batch_op.drop_column("paid_value")

    # ### end Alembic commands ###
