"""add user index 

Revision ID: 8453f38157c0
Revises: bf850e1dd5a0
Create Date: 2024-08-08 15:59:29.721390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8453f38157c0'
down_revision = 'bf850e1dd5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_info_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_info_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_info_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_info_mobile'))

    # ### end Alembic commands ###
