"""add active model

Revision ID: 86e3955ec83d
Revises: 66625b9dd851
Create Date: 2024-08-18 04:26:30.271568

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "86e3955ec83d"
down_revision = "66625b9dd851"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active",
        sa.Column(
            "id",
            mysql.BIGINT(),
            autoincrement=True,
            nullable=False,
            comment="Unique ID",
        ),
        sa.Column(
            "active_id", sa.String(length=36), nullable=False, comment="Active UUID"
        ),
        sa.Column(
            "active_name", sa.String(length=255), nullable=False, comment="Active name"
        ),
        sa.Column(
            "active_desc", sa.Text(), nullable=False, comment="Active description"
        ),
        sa.Column("active_type", sa.Integer(), nullable=False, comment="Active type"),
        sa.Column(
            "active_status", sa.Integer(), nullable=False, comment="Active status"
        ),
        sa.Column(
            "active_start_time",
            sa.TIMESTAMP(),
            nullable=False,
            comment="Active start time",
        ),
        sa.Column(
            "active_end_time", sa.TIMESTAMP(), nullable=False, comment="Active end time"
        ),
        sa.Column(
            "active_price",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Active price",
        ),
        sa.Column(
            "active_discount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Active discount",
        ),
        sa.Column(
            "active_discount_type",
            sa.Integer(),
            nullable=False,
            comment="Active discount type",
        ),
        sa.Column(
            "active_discount_desc",
            sa.Text(),
            nullable=False,
            comment="Active discount description",
        ),
        sa.Column("active_filter", sa.Text(), nullable=False, comment="Active filter"),
        sa.Column("active_course", sa.Text(), nullable=False, comment="Active course"),
        sa.Column("created", sa.TIMESTAMP(), nullable=False, comment="Creation time"),
        sa.Column("updated", sa.TIMESTAMP(), nullable=False, comment="Update time"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "active_user_record",
        sa.Column(
            "id",
            mysql.BIGINT(),
            autoincrement=True,
            nullable=False,
            comment="Unique ID",
        ),
        sa.Column(
            "record_id", sa.String(length=36), nullable=False, comment="Record UUID"
        ),
        sa.Column(
            "active_id", sa.String(length=36), nullable=False, comment="Active UUID"
        ),
        sa.Column("user_id", sa.String(length=36), nullable=False, comment="User UUID"),
        sa.Column(
            "price",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Price of the active",
        ),
        sa.Column(
            "order_id", sa.String(length=36), nullable=False, comment="Order UUID"
        ),
        sa.Column(
            "status", sa.Integer(), nullable=False, comment="Status of the record"
        ),
        sa.Column("created", sa.TIMESTAMP(), nullable=False, comment="Creation time"),
        sa.Column("updated", sa.TIMESTAMP(), nullable=False, comment="Update time"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("active_user_record")
    op.drop_table("active")
    # ### end Alembic commands ###
