"""add course keys words

Revision ID: 92cbdc762a0f
Revises: 35619240774c
Create Date: 2025-02-05 04:08:18.853986

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92cbdc762a0f"
down_revision = "35619240774c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "course_keywords", sa.Text(), nullable=False, comment="Course keywords"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_course", schema=None) as batch_op:
        batch_op.drop_column("course_keywords")

    # ### end Alembic commands ###
