"""add active index

Revision ID: a1913820566f
Revises: 86e3955ec83d
Create Date: 2024-08-18 04:44:05.196016

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a1913820566f"
down_revision = "86e3955ec83d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("active", schema=None) as batch_op:
        batch_op.alter_column(
            "active_course",
            existing_type=mysql.TEXT(),
            type_=sa.String(length=36),
            existing_comment="Active course",
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_active_active_end_time"), ["active_end_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_active_active_start_time"),
            ["active_start_time"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_active_active_status"), ["active_status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("active", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_active_active_status"))
        batch_op.drop_index(batch_op.f("ix_active_active_start_time"))
        batch_op.drop_index(batch_op.f("ix_active_active_end_time"))
        batch_op.alter_column(
            "active_course",
            existing_type=sa.String(length=36),
            type_=mysql.TEXT(),
            existing_comment="Active course",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
