"""empty message

Revision ID: bcf2a9657162
Revises: b6cbcf622c0a
Create Date: 2025-04-29 12:52:04.880611

"""

from alembic import op

# revision identifiers, used by Alembic.

revision = "bcf2a9657162"
down_revision = "b6cbcf622c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE active_user_record SET status = 4101 WHERE status = 0")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("UPDATE active_user_record SET status = 0 WHERE status = 4101")
