"""add_general_infomation

Revision ID: e69662556dc3
Revises: 15cc32aebd22
Create Date: 2025-07-12 17:13:54.268812

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e69662556dc3"
down_revision = "15cc32aebd22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_general_information",
        sa.Column(
            "id",
            mysql.BIGINT(),
            autoincrement=True,
            nullable=False,
            comment="Unique ID",
        ),
        sa.Column("user_id", sa.String(length=36), nullable=False, comment="User ID"),
        sa.Column(
            "general_information",
            sa.Text(),
            nullable=False,
            comment="General information content",
        ),
        sa.Column("shifu_id", sa.String(length=36), nullable=False, comment="Shifu ID"),
        sa.Column(
            "shifu_outline_id",
            sa.String(length=36),
            nullable=False,
            comment="Shifu outline ID",
        ),
        sa.Column(
            "shifu_block_id",
            sa.String(length=36),
            nullable=False,
            comment="Shifu block ID",
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), nullable=False, comment="Creation time"
        ),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False, comment="Update time"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_general_information", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_general_information_shifu_block_id"),
            ["shifu_block_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_general_information_shifu_id"),
            ["shifu_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_general_information_shifu_outline_id"),
            ["shifu_outline_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_general_information_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("profile_item", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment="",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_value_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment="",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_show_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment="",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_prompt_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment="",
            existing_nullable=False,
        )

    with op.batch_alter_table("profile_item_i18n", schema=None) as batch_op:
        batch_op.alter_column(
            "conf_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment="",
            existing_nullable=False,
        )

    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment="",
            existing_nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="",
            existing_nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    with op.batch_alter_table("profile_item_i18n", schema=None) as batch_op:
        batch_op.alter_column(
            "conf_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="",
            existing_nullable=False,
        )

    with op.batch_alter_table("profile_item", schema=None) as batch_op:
        batch_op.alter_column(
            "profile_prompt_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_show_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_value_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "profile_type",
            existing_type=mysql.INTEGER(display_width=11),
            comment=None,
            existing_comment="",
            existing_nullable=False,
        )

    with op.batch_alter_table("user_general_information", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_general_information_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_general_information_shifu_outline_id"))
        batch_op.drop_index(batch_op.f("ix_user_general_information_shifu_id"))
        batch_op.drop_index(batch_op.f("ix_user_general_information_shifu_block_id"))

    op.drop_table("user_general_information")
    # ### end Alembic commands ###
