"""initial migration

Revision ID: fa335667eb18
Revises: 
Create Date: 2024-08-07 23:20:07.319627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa335667eb18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_control_result',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='Unique ID'),
    sa.Column('chat_id', sa.String(length=36), nullable=False, comment='Chat UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User UUID'),
    sa.Column('text', sa.Text(), nullable=False, comment='Text'),
    sa.Column('check_vendor', sa.String(length=255), nullable=False, comment='Check vendor'),
    sa.Column('check_result', sa.Integer(), nullable=False, comment='Check result'),
    sa.Column('check_resp', sa.Text(), nullable=False, comment='Check response'),
    sa.Column('is_pass', sa.Integer(), nullable=False, comment='Is pass'),
    sa.Column('check_strategy', sa.String(length=30), nullable=False, comment='Check strategy'),
    sa.Column('created', sa.TIMESTAMP(), nullable=False, comment='Creation time'),
    sa.Column('updated', sa.TIMESTAMP(), nullable=False, comment='Update time'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_course_lesson_generation', schema=None) as batch_op:
        batch_op.drop_index('idx_attend_id_ai_course_lesson_generation')
        batch_op.drop_index('idx_course_id_ai_course_lesson_generation')
        batch_op.drop_index('idx_generation_id_ai_course_lesson_generation')
        batch_op.drop_index('idx_lesson_id_ai_course_lesson_generation')
        batch_op.drop_index('idx_script_id_ai_course_lesson_generation')
        batch_op.drop_index('idx_user_id_ai_course_lesson_generation')

    op.drop_table('ai_course_lesson_generation')
    with op.batch_alter_table('admin_info', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('default_model',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               comment='Default model',
               existing_comment='gpt model ',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4-0613'"))
        batch_op.alter_column('user_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='User_state',
               existing_comment='user state',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='user sex',
               existing_comment='0-default ,1-male,2-female',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_birth',
               existing_type=sa.DATE(),
               nullable=True,
               comment='user birth',
               existing_comment='birth',
               existing_server_default=sa.text("'1984-01-01'"))
        batch_op.alter_column('user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='user avatar',
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_email_user_info')
        batch_op.drop_index('idx_mobile_user_info')
        batch_op.drop_index('idx_username_user_info')

    with op.batch_alter_table('ai_course', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='Unique ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_course_id_ai_course')

    with op.batch_alter_table('ai_course_buy_record', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Record UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_course_id_ai_course_buy_record')
        batch_op.drop_index('idx_record_id_ai_course_buy_record')
        batch_op.drop_index('idx_user_id_ai_course_buy_record')

    with op.batch_alter_table('ai_course_lesson_attend', schema=None) as batch_op:
        batch_op.alter_column('attend_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Status of the attend: 0-not started, 1-in progress, 2-completed',
               existing_comment='Status of the attend 0-未开始 1-进行中 2-已结束',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('script_index',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Status of the attend: 0-not started, 1-in progress, 2-completed',
               existing_comment='script index',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('idx_attend_id_ai_course_lesson_attend')
        batch_op.drop_index('idx_course_id_ai_course_lesson_attend')
        batch_op.drop_index('idx_lesson_id_ai_course_lesson_attend')
        batch_op.drop_index('idx_user_id_ai_course_lesson_attend')

    with op.batch_alter_table('ai_course_lesson_attend_association', schema=None) as batch_op:
        batch_op.alter_column('association_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('from_attend_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               comment='Attend UUID',
               existing_comment='From Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('to_attend_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               comment='Attend UUID',
               existing_comment='To Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('association_status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Status of the attend: 0-not started, 1-in progress, 2-completed',
               existing_comment='Conversion state',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('ix_ass_id')
        batch_op.drop_index('ix_from_attend_id')
        batch_op.drop_index('ix_to_attend_id')
        batch_op.drop_index('ix_user_id')

    with op.batch_alter_table('ai_course_lesson_attendscript', schema=None) as batch_op:
        batch_op.alter_column('attend_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Script UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_attend_id_ai_course_lesson_attendscript')
        batch_op.drop_index('idx_course_id_ai_course_lesson_attendscript')
        batch_op.drop_index('idx_lesson_id_ai_course_lesson_attendscript')
        batch_op.drop_index('idx_script_id_ai_course_lesson_attendscript')
        batch_op.drop_index('idx_user_id_ai_course_lesson_attendscript')

    with op.batch_alter_table('ai_lesson', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='Unique ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('lesson_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Lesson type',
               existing_comment='0 默认 1 体验课 2 系统课 3 扩展课',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('pre_lesson_no',
               existing_type=mysql.VARCHAR(length=255),
               comment='pre_lesson_no',
               existing_comment='pre lesson no',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_course_id_ai_lesson')
        batch_op.drop_index('idx_lesson_id_ai_lesson')
        batch_op.create_foreign_key(None, 'ai_course', ['course_id'], ['course_id'])
        batch_op.drop_column('lesson_sale_type')

    with op.batch_alter_table('ai_lesson_script', schema=None) as batch_op:
        batch_op.alter_column('script_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Script UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_prompt',
               existing_type=mysql.TEXT(),
               comment='Script prompt',
               existing_comment='Script content',
               existing_nullable=False)
        batch_op.alter_column('script_model',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Script model',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_temprature',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='Script Temprature',
               existing_nullable=False,
               existing_server_default=sa.text("'0.80'"))
        batch_op.alter_column('script_check_flag',
               existing_type=mysql.TEXT(),
               nullable=False,
               comment='Script check flag')
        batch_op.alter_column('script_ui_profile',
               existing_type=mysql.TEXT(),
               comment='Script UI profile',
               existing_comment='Script check content',
               existing_nullable=False)
        batch_op.alter_column('script_other_conf',
               existing_type=mysql.TEXT(),
               comment='Other configurations of the script',
               existing_comment='脚本的其他配置',
               existing_nullable=False)
        batch_op.drop_index('idx_lesson_id_ai_lesson_script')
        batch_op.drop_index('idx_script_id_ai_lesson_script')
        batch_op.create_foreign_key(None, 'ai_lesson', ['lesson_id'], ['lesson_id'])

    with op.batch_alter_table('user_conversion', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_source',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               comment='Conversion type',
               existing_comment='Conversion Source ',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_conversion_id_user_conversion')
        batch_op.drop_index('idx_conversion_uuid_user_conversion')
        batch_op.drop_index('idx_user_id_user_conversion')

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('default_model',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               comment='Default model',
               existing_comment='gpt model ',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4-0613'"))
        batch_op.alter_column('user_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='User_state',
               existing_comment='user state',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='user sex',
               existing_comment='0-default ,1-male,2-female',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_birth',
               existing_type=sa.DATE(),
               nullable=True,
               comment='user birth',
               existing_comment='birth',
               existing_server_default=sa.text("'1984-01-01'"))
        batch_op.alter_column('user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='user avatar',
               existing_server_default=sa.text("''"))
        batch_op.drop_index('idx_email_user_info')
        batch_op.drop_index('idx_mobile_user_info')
        batch_op.drop_index('idx_username_user_info')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('profile_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0 default, 1 system configuration, 2 user configuration, 3 course configuration',
               existing_comment='0 默认,1 系统配置,2 用户配置，3 课程配置',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('idx_user_id_user_profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_user_profile', ['user_id'], unique=False)
        batch_op.alter_column('profile_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0 默认,1 系统配置,2 用户配置，3 课程配置',
               existing_comment='0 default, 1 system configuration, 2 user configuration, 3 course configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.create_index('idx_username_user_info', ['username'], unique=False)
        batch_op.create_index('idx_mobile_user_info', ['mobile'], unique=False)
        batch_op.create_index('idx_email_user_info', ['email'], unique=False)
        batch_op.alter_column('user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='user avatar',
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_birth',
               existing_type=sa.DATE(),
               nullable=False,
               comment='birth',
               existing_comment='user birth',
               existing_server_default=sa.text("'1984-01-01'"))
        batch_op.alter_column('user_sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='0-default ,1-male,2-female',
               existing_comment='user sex',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='user state',
               existing_comment='User_state',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('default_model',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               comment='gpt model ',
               existing_comment='Default model',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4-0613'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('user_conversion', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_user_conversion', ['user_id'], unique=False)
        batch_op.create_index('idx_conversion_uuid_user_conversion', ['conversion_uuid'], unique=False)
        batch_op.create_index('idx_conversion_id_user_conversion', ['conversion_id'], unique=False)
        batch_op.alter_column('conversion_uuid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_source',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               comment='Conversion Source ',
               existing_comment='Conversion type',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('conversion_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Conversion UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_lesson_script', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_script_id_ai_lesson_script', ['script_id'], unique=False)
        batch_op.create_index('idx_lesson_id_ai_lesson_script', ['lesson_id'], unique=False)
        batch_op.alter_column('script_other_conf',
               existing_type=mysql.TEXT(),
               comment='脚本的其他配置',
               existing_comment='Other configurations of the script',
               existing_nullable=False)
        batch_op.alter_column('script_ui_profile',
               existing_type=mysql.TEXT(),
               comment='Script check content',
               existing_comment='Script UI profile',
               existing_nullable=False)
        batch_op.alter_column('script_check_flag',
               existing_type=mysql.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='Script check flag')
        batch_op.alter_column('script_temprature',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment=None,
               existing_comment='Script Temprature',
               existing_nullable=False,
               existing_server_default=sa.text("'0.80'"))
        batch_op.alter_column('script_model',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Script model',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_prompt',
               existing_type=mysql.TEXT(),
               comment='Script content',
               existing_comment='Script prompt',
               existing_nullable=False)
        batch_op.alter_column('lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Script UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_sale_type', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='0 默认 1 体验课 2 系统课 3 扩展课'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_lesson_id_ai_lesson', ['lesson_id'], unique=False)
        batch_op.create_index('idx_course_id_ai_lesson', ['course_id'], unique=False)
        batch_op.alter_column('pre_lesson_no',
               existing_type=mysql.VARCHAR(length=255),
               comment='pre lesson no',
               existing_comment='pre_lesson_no',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0 默认 1 体验课 2 系统课 3 扩展课',
               existing_comment='Lesson type',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='Unique ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('ai_course_lesson_attendscript', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_ai_course_lesson_attendscript', ['user_id'], unique=False)
        batch_op.create_index('idx_script_id_ai_course_lesson_attendscript', ['script_id'], unique=False)
        batch_op.create_index('idx_lesson_id_ai_course_lesson_attendscript', ['lesson_id'], unique=False)
        batch_op.create_index('idx_course_id_ai_course_lesson_attendscript', ['course_id'], unique=False)
        batch_op.create_index('idx_attend_id_ai_course_lesson_attendscript', ['attend_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('script_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Script UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('attend_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_course_lesson_attend_association', schema=None) as batch_op:
        batch_op.create_index('ix_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_to_attend_id', ['to_attend_id'], unique=False)
        batch_op.create_index('ix_from_attend_id', ['from_attend_id'], unique=False)
        batch_op.create_index('ix_ass_id', ['association_id'], unique=False)
        batch_op.alter_column('association_status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Conversion state',
               existing_comment='Status of the attend: 0-not started, 1-in progress, 2-completed',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('to_attend_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               comment='To Attend UUID',
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('from_attend_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               comment='From Attend UUID',
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('association_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_course_lesson_attend', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_ai_course_lesson_attend', ['user_id'], unique=False)
        batch_op.create_index('idx_lesson_id_ai_course_lesson_attend', ['lesson_id'], unique=False)
        batch_op.create_index('idx_course_id_ai_course_lesson_attend', ['course_id'], unique=False)
        batch_op.create_index('idx_attend_id_ai_course_lesson_attend', ['attend_id'], unique=False)
        batch_op.alter_column('script_index',
               existing_type=mysql.INTEGER(display_width=11),
               comment='script index',
               existing_comment='Status of the attend: 0-not started, 1-in progress, 2-completed',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Status of the attend 0-未开始 1-进行中 2-已结束',
               existing_comment='Status of the attend: 0-not started, 1-in progress, 2-completed',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Lesson UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('attend_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Attend UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_course_buy_record', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_ai_course_buy_record', ['user_id'], unique=False)
        batch_op.create_index('idx_record_id_ai_course_buy_record', ['record_id'], unique=False)
        batch_op.create_index('idx_course_id_ai_course_buy_record', ['course_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('record_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Record UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('ai_course', schema=None) as batch_op:
        batch_op.create_index('idx_course_id_ai_course', ['course_id'], unique=False)
        batch_op.alter_column('course_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='Course UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='Unique ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('admin_info', schema=None) as batch_op:
        batch_op.create_index('idx_username_user_info', ['username'], unique=False)
        batch_op.create_index('idx_mobile_user_info', ['mobile'], unique=False)
        batch_op.create_index('idx_email_user_info', ['email'], unique=False)
        batch_op.alter_column('user_avatar',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='user avatar',
               existing_server_default=sa.text("''"))
        batch_op.alter_column('user_birth',
               existing_type=sa.DATE(),
               nullable=False,
               comment='birth',
               existing_comment='user birth',
               existing_server_default=sa.text("'1984-01-01'"))
        batch_op.alter_column('user_sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='0-default ,1-male,2-female',
               existing_comment='user sex',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_state',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='user state',
               existing_comment='User_state',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('default_model',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               comment='gpt model ',
               existing_comment='Default model',
               existing_nullable=False,
               existing_server_default=sa.text("'gpt-4-0613'"))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_comment='User UUID',
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    op.create_table('ai_course_lesson_generation',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='Unique ID'),
    sa.Column('generation_id', mysql.CHAR(length=36), server_default=sa.text("''"), nullable=False, comment='Generation UUID'),
    sa.Column('lesson_id', mysql.CHAR(length=36), server_default=sa.text("''"), nullable=False, comment='Lesson UUID'),
    sa.Column('course_id', mysql.CHAR(length=36), server_default=sa.text("''"), nullable=False, comment='Course UUID'),
    sa.Column('script_id', mysql.CHAR(length=36), server_default=sa.text("''"), nullable=False, comment='Script UUID'),
    sa.Column('attend_id', mysql.CHAR(length=36), server_default=sa.text("''"), nullable=False, comment='Attend UUID'),
    sa.Column('model', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False, comment='Model of the generation'),
    sa.Column('prompt', mysql.TEXT(), nullable=False, comment='Prompt for the generation'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='Content of the generation'),
    sa.Column('input_tokens', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Input tokens of the generation'),
    sa.Column('output_tokens', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Output tokens of the generation'),
    sa.Column('index', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Index of the generation'),
    sa.Column('user_id', mysql.CHAR(length=36), server_default=sa.text("''"), nullable=False, comment='User UUID'),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Status of the generation'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Creation time'),
    sa.Column('updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='Update time'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ai_course_lesson_generation', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_ai_course_lesson_generation', ['user_id'], unique=False)
        batch_op.create_index('idx_script_id_ai_course_lesson_generation', ['script_id'], unique=False)
        batch_op.create_index('idx_lesson_id_ai_course_lesson_generation', ['lesson_id'], unique=False)
        batch_op.create_index('idx_generation_id_ai_course_lesson_generation', ['generation_id'], unique=False)
        batch_op.create_index('idx_course_id_ai_course_lesson_generation', ['course_id'], unique=False)
        batch_op.create_index('idx_attend_id_ai_course_lesson_generation', ['attend_id'], unique=False)

    op.drop_table('risk_control_result')
    # ### end Alembic commands ###
