
BUY_STATUS_INIT = 501
BUY_STATUS_SUCCESS = 502
BUY_STATUS_REFUND = 503


ATTEND_STATUS_NOT_STARTED = 601
ATTEND_STATUS_IN_PROGRESS = 602
ATTEND_STATUS_COMPLETED = 603
ATTEND_STATUS_REFUND = 604


BUY_STATUS_TYPES = {
    "初始化":BUY_STATUS_INIT,
    "购买成功":BUY_STATUS_SUCCESS,
    "退款":BUY_STATUS_REFUND
}

ATTEND_STATUS_TYPES = {
    "未开始":ATTEND_STATUS_NOT_STARTED,
    "进行中":ATTEND_STATUS_IN_PROGRESS,
    "已完成":ATTEND_STATUS_COMPLETED,
    "退款":ATTEND_STATUS_REFUND
}