ACTIVE_STATUS = {
    0: "无效",
    1: "有效",
}


ACTIVE_JOIN_TYPE_AUTO = 2101
ACTIVE_JOIN_TYPE_EVENT = 2102
ACTIVE_JOIN_TYPE_MANUAL = 2103

ACTIVE_JOIN_TYPE_MAP = {
    ACTIVE_JOIN_TYPE_AUTO: "自动",
    ACTIVE_JOIN_TYPE_EVENT: "事件",
    ACTIVE_JOIN_TYPE_MANUAL: "手动",
}
