from flaskr.i18n import _

ORDER_STATUS_INIT = 501
ORDER_STATUS_SUCCESS = 502
ORDER_STATUS_REFUND = 503
ORDER_STATUS_TO_BE_PAID = 504
ORDER_STATUS_TIMEOUT = 505

LEARN_STATUS_NOT_STARTED = 601
LEARN_STATUS_IN_PROGRESS = 602
LEARN_STATUS_COMPLETED = 603
LEARN_STATUS_REFUND = 604
LEARN_STATUS_LOCKED = 605
LEARN_STATUS_UNAVAILABLE = 606
LEARN_STATUS_BRANCH = 607
LEARN_STATUS_RESET = 608
LEARN_STATUS_NOT_EXIST = -1
ORDER_STATUS_TYPES = {
    _("ORDER.ORDER_STATUS_INIT"): ORDER_STATUS_INIT,
    _("ORDER.ORDER_STATUS_SUCCESS"): ORDER_STATUS_SUCCESS,
    _("ORDER.ORDER_STATUS_REFUND"): ORDER_STATUS_REFUND,
    _("ORDER.ORDER_STATUS_TO_BE_PAID"): ORDER_STATUS_TO_BE_PAID,
    _("ORDER.ORDER_STATUS_TIMEOUT"): ORDER_STATUS_TIMEOUT,
}

ORDER_STATUS_VALUES = {
    ORDER_STATUS_INIT: _("ORDER.ORDER_STATUS_INIT"),
    ORDER_STATUS_SUCCESS: _("ORDER.ORDER_STATUS_SUCCESS"),
    ORDER_STATUS_REFUND: _("ORDER.ORDER_STATUS_REFUND"),
    ORDER_STATUS_TO_BE_PAID: _("ORDER.ORDER_STATUS_TO_BE_PAID"),
    ORDER_STATUS_TIMEOUT: _("ORDER.ORDER_STATUS_TIMEOUT"),
}

LEARN_STATUS_TYPES = {
    _("ORDER.LEARN_STATUS_NOT_STARTED"): LEARN_STATUS_NOT_STARTED,
    _("ORDER.LEARN_STATUS_IN_PROGRESS"): LEARN_STATUS_IN_PROGRESS,
    _("ORDER.LEARN_STATUS_COMPLETED"): LEARN_STATUS_COMPLETED,
    _("ORDER.LEARN_STATUS_REFUND"): LEARN_STATUS_REFUND,
    _("ORDER.LEARN_STATUS_LOCKED"): LEARN_STATUS_LOCKED,
    _("ORDER.LEARN_STATUS_UNAVAILABLE"): LEARN_STATUS_UNAVAILABLE,
    _("ORDER.LEARN_STATUS_BRANCH"): LEARN_STATUS_BRANCH,
    _("ORDER.LEARN_STATUS_RESET"): LEARN_STATUS_RESET,
}


def get_learn_status_values():
    return {
        LEARN_STATUS_NOT_STARTED: _("ORDER.LEARN_STATUS_NOT_STARTED"),
        LEARN_STATUS_IN_PROGRESS: _("ORDER.LEARN_STATUS_IN_PROGRESS"),
        LEARN_STATUS_COMPLETED: _("ORDER.LEARN_STATUS_COMPLETED"),
        LEARN_STATUS_REFUND: _("ORDER.LEARN_STATUS_REFUND"),
        LEARN_STATUS_LOCKED: _("ORDER.LEARN_STATUS_LOCKED"),
        LEARN_STATUS_UNAVAILABLE: _("ORDER.LEARN_STATUS_UNAVAILABLE"),
        LEARN_STATUS_BRANCH: _("ORDER.LEARN_STATUS_BRANCH"),
        LEARN_STATUS_RESET: _("ORDER.LEARN_STATUS_RESET"),
        LEARN_STATUS_NOT_EXIST: _("ORDER.LEARN_STATUS_LOCKED"),
    }
