
BUY_STATUS_INIT = 501
BUY_STATUS_SUCCESS = 502
BUY_STATUS_REFUND = 503


ATTEND_STATUS_NOT_STARTED = 601
ATTEND_STATUS_IN_PROGRESS = 602
ATTEND_STATUS_COMPLETED = 603
ATTEND_STATUS_REFUND = 604
ATTEND_STATUS_LOCKED = 605
ATTEND_STATUS_UNAVAILABE = 606
ATTEND_STATUS_BRANCH = 607

BUY_STATUS_TYPES = {
    "初始化":BUY_STATUS_INIT,
    "购买成功":BUY_STATUS_SUCCESS,
    "退款":BUY_STATUS_REFUND
}

ATTEND_STATUS_TYPES = {
    "可学习":ATTEND_STATUS_NOT_STARTED,
    "正在学":ATTEND_STATUS_IN_PROGRESS,
    "已完成":ATTEND_STATUS_COMPLETED,
    "退款":ATTEND_STATUS_REFUND,
    "未解锁":ATTEND_STATUS_LOCKED,
    "不可用":ATTEND_STATUS_UNAVAILABE,
    "分支":ATTEND_STATUS_BRANCH,
}

ATTEND_STATUS_VALUES = {
   ATTEND_STATUS_NOT_STARTED: "可学习",
  ATTEND_STATUS_IN_PROGRESS:"正在学",
  ATTEND_STATUS_COMPLETED:"已完成",
  ATTEND_STATUS_REFUND:"退款",
  ATTEND_STATUS_LOCKED:"未解锁",
  ATTEND_STATUS_UNAVAILABE:"不可用",
    ATTEND_STATUS_BRANCH:"分支"
}