COUPON_TYPE_FIXED = 701
COUPON_TYPE_PERCENT = 702

COUPON_TYPE_TYPES = {"固定金额": COUPON_TYPE_FIXED, "百分比": COUPON_TYPE_PERCENT}

COUPON_TYPE_VALUES = {
    COUPON_TYPE_FIXED: "固定金额",
    COUPON_TYPE_PERCENT: "百分比",
}


COUPON_APPLY_TYPE_ALL = 801
COUPON_APPLY_TYPE_SPECIFIC = 802

COUPON_APPLY_TYPE_TYPES = {
    "通用折扣码": COUPON_APPLY_TYPE_ALL,
    "一单一码": COUPON_APPLY_TYPE_SPECIFIC,
}


COUPON_APPLY_TYPE_VALUES = {
    COUPON_APPLY_TYPE_ALL: "通用折扣码",
    COUPON_APPLY_TYPE_SPECIFIC: "一单一码",
}


COUPON_STATUS_INACTIVE = 901
COUPON_STATUS_ACTIVE = 902
COUPON_STATUS_USED = 903
COUPON_STATUS_TIMEOUT = 904


COUPON_STATUS_TYPES = {
    "未激活": COUPON_STATUS_INACTIVE,
    "激活": COUPON_STATUS_ACTIVE,
    "已使用": COUPON_STATUS_USED,
    "已过期": COUPON_STATUS_TIMEOUT,
}

COUPON_STATUS_VALUES = {
    COUPON_STATUS_INACTIVE: "未激活",
    COUPON_STATUS_ACTIVE: "激活",
    COUPON_STATUS_USED: "已使用",
    COUPON_STATUS_TIMEOUT: "已过期",
}
