from .chat import register_chat_route
from .common import register_common_handler
from .user import register_user_handler
from .resource import register_resource_route
from .contact import register_contact_handler
from .document import register_document_handler
from .schedule import register_schedule_handler
from .todo import register_todo_handler
from .plugin import register_test_plug
from .api import register_api_handler
from .lesson import register_lesson_handler
from .study import register_study_handler