FROM node:20.11.1 AS base
# use pnpm
RUN corepack enable
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"


# set work directory
WORKDIR /app

# install project dependencies
# copy package.json and package-lock.json files
COPY package*.json ./

# copy ecosystem.config.js file
COPY ecosystem.config.js ./

# copy project source code
COPY . .

RUN pnpm install

# expose port
EXPOSE 5000

# start service
CMD ["pnpm", "run", "start:dev"]
