# LLM Service Agreement

## User Agreement

Welcome to sign this "User Agreement" (hereinafter referred to as "this Agreement") and use the AI Shifu (as defined below) service.

### Relevant Definitions

- **AI Shifu**: Refers to the personalized AI teaching product operated by Beijing Chanchan Shanmu Technology Co., Ltd.
- **AI Shifu Service Provider**: Refers to the internet information and software technology service provider, Beijing Chanchan Shanmu Technology Co., Ltd., for AI Shifu.
- **User or You**: Refers to the person using AI Shifu or the services.

### Scope of the Agreement

This agreement is signed between you and Beijing Chanchan Shanmu Technology Co., Ltd. and becomes effective once you confirm acceptance or upon your use of AI Shifu. Unless expressly stated otherwise, any new features, products, or services added to the platform will unconditionally apply to this Agreement.

### Account and Usage Instructions

When using AI Shifu services, you need to:

- Register a user account
- Complete real-name authentication

#### User Eligibility

Please confirm that before you begin the registration process and use AI Shifu services, you have the civil capacity required by the laws of the People's Republic of China corresponding to your actions. If you do not have such civil capacity, then you and your guardian shall bear all consequences of your registration. You acknowledge that if a person without civil capacity or with limited civil capacity registers as an AI Shifu user, the service agreement between that person and AI Shifu is invalid from the outset. Once discovered, AI Shifu has the right to immediately stop services or cancel the account.

#### Account Registration

Account registration refers to the process where a user logs in to AI Shifu, fills in relevant information as required, and confirms the agreement to comply with this Agreement. If there is evidence or AI Shifu determines, based on related rules, that you have improperly registered or misused multiple AI Shifu accounts, AI Shifu may take measures such as freezing or closing accounts and refusing services. If this causes losses to AI Shifu or related parties, you shall bear the responsibility for compensation.

#### Account Security

You have the right to log in to AI Shifu using the mobile number you set and the password you created. Your account is set and maintained by you, and AI Shifu will never ask for your account password. Therefore, AI Shifu is not responsible for any losses or consequences resulting from your account being compromised due to voluntary disclosure or third-party attacks. You should seek judicial or administrative remedies against the infringing party.

#### Account Transfer

You can transfer your account only under legal provisions, judicial rulings, or after complying with the AI Shifu platform’s rules and obtaining AI Shifu's consent. Once transferred, all rights and obligations under the account will be transferred to the new owner. Otherwise, any unauthorized transfer will result in AI Shifu having the right to pursue breach of contract, and you will bear any resulting consequences.

#### Update and Maintenance

You must promptly update your information. In cases where AI Shifu, as the platform service provider, is legally required to verify certain users' information, AI Shifu will periodically verify your information. You must cooperate by providing up-to-date, accurate, and complete information. AI Shifu may send inquiries or require corrections, including re-verification, and may suspend or terminate services if:

- AI Shifu is unable to contact you using the last provided information;
- You fail to provide timely information as requested by AI Shifu;
- The information you provide is obviously inaccurate, or administrative and judicial authorities determine your information to be invalid. You will bear all losses and adverse consequences resulting from this.

### Rights and Obligations of the Platform

1. AI Shifu is obligated to maintain the normal operation of the platform within the limits of existing technology and strives to improve the user experience.
2. AI Shifu will promptly respond to issues related to products or services encountered during registration or use, within the timeframe stipulated by law.
3. In case of inappropriate behavior by users or situations where AI Shifu deems service termination necessary, AI Shifu has the right to block information or terminate services and notify the relevant authorities. If you disagree with the measures, you may provide evidence to explain your position.
4. AI Shifu reserves the right to use your input and outputs generated by AI Shifu for further development and training, and you fully understand and accept such usage without claiming rights against AI Shifu.
5. AI Shifu will take all reasonable measures to ensure the safety and stability of the AI Shifu network.
6. If services are provided free of charge, you understand and agree that adjustments may be made based on research progress. You promise not to pursue any liability against AI Shifu for adjustments or the expiration of free service benefits.
7. You are not allowed to delete, modify, or obscure the deep synthesis service marks generated in AI Shifu's output content.

### Your Rights and Obligations

1. You have the right to enjoy the services provided by AI Shifu as outlined in this Agreement, including the question-answer dialogue generation service. AI Shifu reserves the right to add or reduce service content as necessary.
2. You should not engage in improper conduct that disrupts the normal order of the platform while using AI Shifu.
3. You may not input or induce AI Shifu to generate content that includes the following, or AI Shifu may delete or block such content and report it to the authorities:

   - Inciting resistance or sabotage of constitutional or legal provisions;
   - Inciting subversion of state power or the socialist system;
   - Inciting division of the country or destruction of national unity;
   - Inciting national hatred or discrimination, or undermining national unity;
   - Discriminatory content related to race, gender, religion, or region;
   - Fabricating or distorting facts, spreading rumors, or disturbing social order;
   - Promoting feudal superstition, obscenity, pornography, gambling, violence, murder, terrorism, or instigating crime;
   - Publicly insulting or defaming others, or maliciously attacking others;
   - Damaging the reputation of state organs;
   - Other content inappropriate for publication on AI Shifu or violating the constitution, laws, or administrative regulations.

4. You shall not misuse AI Shifu in the following ways:

   - In a way that infringes on any person’s rights;
   - Engaging in reverse engineering of AI Shifu’s algorithms, source codes, or mechanisms;
   - Using AI Shifu to develop, train, or improve algorithms, models, etc., that directly or indirectly compete with Beijing Chanchan Shanmu Technology Co., Ltd.;
   - Using AI Shifu in any services that require subject qualifications, including but not limited to medical services, legal services, psychological counseling, or infrastructure development;
   - Any other use that may harm the interests of Beijing Chanchan Shanmu Technology Co., Ltd.

5. If you provide services to any third party using AI Shifu, the corresponding rights, obligations, and responsibilities are entirely borne by you, and AI Shifu is not liable for any resulting losses.

6. When using AI Shifu abroad, you should comply with all laws, regulations, and policies of foreign entities such as the United States, the European Union, and/or other government bodies.

### Termination of Service Agreement

1. You have the right to terminate this agreement through any of the following methods:

   - By canceling your account;
   - By stopping the use of the platform before any changes take effect and explicitly expressing unwillingness to accept the changes;
   - By expressing unwillingness to continue using AI Shifu services, meeting the platform’s termination conditions. Once your cancellation request is submitted and approved by AI Shifu, your account will be canceled, and the service relationship with AI Shifu will be terminated.

2. AI Shifu may terminate services by canceling the user account under the following conditions:

   - If you violate the provisions of this agreement, AI Shifu may terminate the agreement in accordance with the breach of contract provisions. AI Shifu will notify you upon termination. However, if you re-register as an AI Shifu user directly or indirectly in another’s name after service termination, AI Shifu has the right to terminate services again unilaterally.
   - If AI Shifu contacts you using the information provided during registration and finds that the provided phone number no longer exists or is unable to receive messages, AI Shifu may notify you via other contact information provided during registration to make changes. If you fail to do so within three working days or AI Shifu cannot contact you based on your registration details, AI Shifu may terminate services.
   - If AI Shifu finds that the primary information in your registration is false;
   - If this service agreement is terminated or updated, and you explicitly express unwillingness to accept the new service agreement;
   - If you publish illegal information, infringe on the legitimate rights of others, or engage in other serious illegal or breach behaviors on the AI Shifu platform;
   - In addition to the above circumstances, if you repeatedly violate the AI Shifu platform rules, and the violations are severe, AI Shifu may seal your account according to platform rules;
   - Any other situations where AI Shifu believes service should be terminated.

3. After the termination of the agreement, except as otherwise stipulated by law, AI Shifu has no obligation to disclose any information from your account to you or any third party. After termination, AI Shifu retains the following rights:

   - To continue storing various types of information you left on the AI Shifu platform after anonymizing the user data;
   - To pursue any breach of contract that occurred before termination in accordance with this agreement.

### Intellectual Property Rights Regarding Generated Content

1. You fully understand and agree that you may only use AI Shifu and its generated content for non-commercial, personal research and learning purposes. AI Shifu, along with its programs, software, information, data, development documents, and related elements and components, is protected by the laws and regulations of the People’s Republic of China and relevant international treaties. Beijing Chanchan Shanmu Technology Co., Ltd. and related rights holders own the intellectual property rights.

2. Without the written consent of Beijing Chanchan Shanmu Technology Co., Ltd. and related rights holders:

   - You are not entitled to use AI Shifu or its generated content for any commercial purposes;
   - You may not use AI Shifu to develop products or services that compete with AI Shifu.

3. The copyright of any content you input into AI Shifu belongs solely to the original author. If the content has a copyright statement or was reposted from another website with an accompanying copyright statement, the ownership will follow the attached statement.

4. You are responsible for independently managing and using any copyrights for content generated by AI Shifu, and any intellectual property issues arising from such content are your responsibility. Beijing Chanchan Shanmu Technology Co., Ltd. is not liable for any resulting losses, and if any damages occur to the company, it has the right to seek compensation from you.

### Limitation of Liability Regarding Generated Content

1. AI Shifu performs its basic duties in accordance with the law, but does not bear responsibility for the following issues that lead to contractual performance barriers, defects, delays, or changes:

   - Natural disasters, strikes, riots, wars, government actions, judicial or administrative orders, and other force majeure events;
   - Routine or emergency equipment and system maintenance, equipment and system failures, network information and data security issues, and similar factors.

2. Due to the technical limitations of AI Shifu’s service, AI Shifu makes no guarantees regarding the following:

   - That AI Shifu will meet your actual or specific needs or purposes;
   - That AI Shifu is accurate, reliable, functional, available, timely, secure, error-free, uninterrupted, continuously stable, and free of any faults;
   - While AI Shifu’s content is filtered by AI algorithms, some content may still have flaws, be unreasonable, or cause discomfort to users. The generated content does not represent the views or attitudes of the AI Shifu team;
   - The accuracy, stability, or completeness of the code, programs, and their referenced content within AI Shifu.

### User Information Protection and Authorization

For any non-personal information you provide, publish, or form during your use of AI Shifu’s services, there is no transfer of intellectual property rights, portrait rights, or similar rights due to the act of uploading or publishing. Unless otherwise stated, within the scope permitted by law, you grant Beijing Chanchan Shanmu Technology Co., Ltd. and its affiliates a non-exclusive, global, perpetual, and free license to use and sublicense this information to third parties. They also have the right to gather evidence and initiate litigation against third-party infringements.

### Breach of Contract and Handling Methods

If you engage in the following behaviors, it is considered a breach of contract, and AI Shifu has the right to take corresponding actions:

- AI Shifu has the right to review your registration data and product/service usage behavior. If problems are found or suspected, AI Shifu has the right to send inquiries and/or rectification notices. If you do not respond within a reasonable period, AI Shifu may block or delete the registration data or usage behaviors.
- If confirmed by a legally effective judgment or administrative penalty, or if AI Shifu has sufficient facts to believe that you have violated the law or this agreement, AI Shifu has the right to disclose your illegal behavior publicly on the platform in a lawful manner.
- AI Shifu may also take action to delete or restrict your information if it believes it involves malicious or false content, attempts to disrupt the platform’s order, or violates public interest or could seriously damage the legitimate rights and interests of AI Shifu or other users.

### Applicable Law and Dispute Resolution

1. The formation, validity, interpretation, revision, supplementation, termination, enforcement, and dispute resolution of this Agreement shall be governed by the laws of mainland China. If there are no relevant provisions in the law, reference shall be made to business and/or industry practices.

2. If any provision of this Agreement is found to be void, invalid, or unenforceable, it shall be deemed severable and shall not affect the validity and enforceability of the remaining provisions.

### Contact Us

If you have any questions about the agreement while using the product, you can contact us by sending an email to support@ai-shifu.com or using the feedback channels in the product or the contact methods marked on the website.
