ROLE_TEACHER = 1
ROLE_STUDENT = 2
ROLE_UI = 3


ROLE_VALUES = {ROLE_TEACHER: "老师", ROLE_STUDENT: "学生", ROLE_UI: "UI"}


INPUT_TYPE_TEXT = "text"
INPUT_TYPE_CONTINUE = "continue"
INPUT_TYPE_START = "start"
INPUT_TYPE_SELECT = "select"
INPUT_TYPE_PHONE = "phone"
INPUT_TYPE_CHECKCODE = "checkcode"
INPUT_TYPE_REQUIRE_LOGIN = "require_login"
INPUT_TYPE_LOGIN = "login"
INPUT_TYPE_BRANCH = "branch"
INPUT_TYPE_ASK = "ask"
