## 使用一个官方Python运行时作为父镜像
#FROM python:3.11
#
#RUN apt-get update && apt-get install -y python3-pip


FROM registry.cn-hangzhou.aliyuncs.com/kattgatt-base/python-smart-home-plugins:v4
# 设置工作目录
WORKDIR /app

ENV PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
ENV PIP_TRUSTED_HOST=mirrors.aliyun.com

## 安装依赖
COPY requirements.txt .
RUN pip install -r requirements.txt


# 复制当前目录内容到容器的/app内
WORKDIR /app
COPY . .

# 声明服务运行在5000端口
EXPOSE 5800

# 声明其他变量
#ENV ENVIRONMENT=dev
#ENV ENVIRONMENT=prod_k8s
ENV ENVIRONMENT=uat_k8s


# 启动flask服务


CMD gunicorn -w 4 -b 0.0.0.0:5800 "flaskr:create_app('$ENVIRONMENT')"  --timeout 300 --log-level debug --access-logfile /var/log/app.log  --capture-output